In [119]:
import glob
import cv2
import pandas as pd
from keras import models
from keras import layers
from numpy.random import seed
seed(123)
from tensorflow import set_random_seed
set_random_seed(123)
import matplotlib.pyplot as plt
import scipy
from PIL import Image
from scipy import ndimage
import numpy as np
from keras.models import model_from_json
from keras.applications.inception_v3 import InceptionV3
from keras.applications.resnet50 import ResNet50
from keras.preprocessing import image
from keras.applications.resnet50 import preprocess_input, decode_predictions
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import os, shutil
from sklearn.cluster import KMeans

In [87]:
for im in glob.glob('../early_predictions/images/*/*'):
    if im[-4:] not '.jpg':
        new_filename = im + '.jpg'
        os.rename(im, new_filename)
    else:
        pass

## ResNet50 

In [120]:
resnet_weights_path = '../input/resnet50/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5'

my_new_model = models.Sequential()
my_new_model.add(ResNet50(include_top=False, pooling='avg', weights="imagenet"))

# Say not to train first layer (ResNet) model. It is already trained
my_new_model.layers[0].trainable = False

In [124]:
def extract_vector_df(path):
    resnet_feature_list = []
    user_list = []
    img_list = []

    for im in glob.glob(path):
        try: 
            print(im.split('/')[3])
            user_list.append(im.split('/')[3])
            img_list.append(im)
            im = cv2.imread(im)
            im = cv2.resize(im,(224,224))
            img = preprocess_input(np.expand_dims(im.copy(), axis=0))
            resnet_feature = my_new_model.predict(img)
            resnet_feature_np = np.array(resnet_feature)
            resnet_feature_list.append(resnet_feature_np.flatten())
        except:
            print('this one is busted')
    return user_list, img_list, resnet_feature_list

In [115]:
# from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img

# # get all the data in the directory split/test (180 images), and reshape them
# data_all = ImageDataGenerator(rescale=1./255).flow_from_directory( 
#         '../early_predictions/images/', 
#         target_size=(224, 224), 
#         batch_size = 2048, 
#         seed = 123)

In [116]:
# images, labels = next(data_all)

In [117]:
# my_new_model.predict(images)

In [125]:
users, images, vectors = extract_vector_df('../early_predictions/images/*/*')

10892
10892
10892
10892
10892
10892
10892
10892
10892
10892
10892
10892
10892
10892
10892
10892
10892
10892
10892
10892
3161
3161
3161
3161
3161
3161
3161
3161
3161
3161
3161
3161
3161
3161
3161
3161
3161
3161
3161
3161
157
157
157
157
157
157
157
157
157
157
157
157
157
157
157
157
157
157
157
157
2079
2079
2079
2079
2079
2079
2079
2079
2079
2079
2079
2079
2079
2079
2079
2079
2079
2079
2079
2079
6627
6627
6627
6627
6627
6627
6627
6627
6627
6627
6627
6627
6627
6627
6627
6627
6627
6627
6627
10603
10603
10603
10603
10603
10603
10603
10603
10603
10603
10603
10603
10603
10603
10603
10603
10603
10603
10603
10603
8923
8923
8923
8923
8923
8923
8923
8923
8923
8923
8923
8923
8923
8923
8923
8923
8923
8923
8923
8923
11725
11725
11725
11725
11725
11725
11725
11725
11725
11725
11725
11725
11725
11725
11725
11725
11725
11725
11725
11725
762
762
762
762
762
762
762
762
762
762
762
762
762
762
762
762
762
762
762
762
11189
11189
11189
11189
11189
11189
11189
11189
11189
11189
11189
11189
11189
11189
1

7543
7543
7543
7543
7543
7543
7543
7543
7543
7543
7543
7543
7543
7543
7543
7543
2633
2633
2633
2633
2633
2633
2633
2633
2633
2633
2633
2633
2633
2633
2633
2633
2633
2633
2633
2633
922
922
922
922
922
922
922
922
922
922
922
922
922
922
922
922
922
922
922
922
9673
9673
9673
9673
9673
9673
9673
9673
9673
9673
9673
9673
9673
9673
9673
9673
9673
9673
9673
9673
6438
6438
6438
6438
6438
6438
6438
6438
6438
6438
6438
6438
6438
6438
6438
6438
6438
6438
6438
6438
9484
9484
9484
9484
9484
9484
9484
9484
9484
9484
9484
9484
9484
9484
9484
9484
9484
9484
9484
9484
1661
1661
1661
1661
1661
1661
1661
1661
1661
1661
1661
1661
1661
1661
1661
1661
1661
1661
1661
1661
10664
10664
10664
10664
10664
10664
10664
10664
10664
10664
10664
10664
10664
10664
10664
10664
10664
10664
10664
10664
3751
3751
3751
3751
3751
3751
3751
3751
3751
3751
3751
3751
3751
3751
3751
3751
3751
3751
3751
3751
6011
6011
6011
6011
6011
6011
6011
6011
6011
6011
6011
6011
6011
6011
6011
6011
6011
6011
6011
6011
6475
6475
6475
6475


170
170
8531
8531
8531
8531
8531
8531
8531
8531
8531
8531
8531
8531
8531
8531
8531
8531
8531
8531
8531
8531
11101
11101
11101
11101
11101
11101
11101
11101
11101
11101
11101
11101
11101
11101
11101
11101
11101
11101
11101
11101
9419
9419
9419
9419
9419
9419
9419
9419
9419
9419
9419
9419
9419
9419
9419
9419
9419
9419
9419
9419
7789
7789
7789
7789
7789
7789
7789
7789
7789
7789
7789
7789
7789
7789
7789
7789
7789
7789
7789
7789
8960
8960
8960
8960
8960
8960
8960
8960
8960
8960
8960
8960
8960
8960
8960
8960
8960
8960
8960
8960
1274
1274
1274
1274
1274
1274
1274
1274
1274
1274
1274
1274
1274
1274
1274
1274
1274
1274
1274
1274
1842
1842
1842
1842
1842
1842
1842
1842
1842
1842
1842
1842
1842
1842
1842
1842
1842
1077
1077
1077
1077
1077
1077
1077
1077
1077
1077
1077
1077
1077
1077
1077
1077
1077
1077
1083
1083
1083
1083
1083
1083
1083
1083
1083
1083
1083
1083
1083
1083
1083
1083
1083
1083
1083
1083
1048
1048
1048
1048
1048
1048
1048
1048
1048
1048
1048
1048
1048
1048
1048
1048
1048
1048
1048
10

In [126]:
vectors

[array([0.40476277, 1.9389986 , 0.        , ..., 1.0818287 , 0.06677113,
        2.3749416 ], dtype=float32),
 array([0.68125784, 0.560113  , 0.03943072, ..., 0.9697671 , 0.        ,
        1.2315458 ], dtype=float32),
 array([0.5991864 , 0.06786992, 0.36496353, ..., 0.        , 0.02230464,
        0.        ], dtype=float32),
 array([0.19345565, 0.02552061, 0.06400478, ..., 0.66542286, 1.4366835 ,
        0.48431468], dtype=float32),
 array([0.21553631, 0.27606928, 0.13081075, ..., 0.29854208, 0.30067647,
        0.37859038], dtype=float32),
 array([1.2974138 , 0.12589423, 0.5886368 , ..., 3.1810327 , 1.3131816 ,
        1.5703467 ], dtype=float32),
 array([0.37541795, 2.171982  , 0.        , ..., 0.24192004, 0.48449138,
        0.85343   ], dtype=float32),
 array([0.61994904, 0.6112355 , 0.12713769, ..., 1.0475026 , 0.95312786,
        0.83006316], dtype=float32),
 array([0.15040074, 2.5803719 , 0.14914453, ..., 0.8895094 , 0.96625185,
        2.6764848 ], dtype=float32),
 array([0.

In [127]:
kmeans = KMeans(n_clusters=20, random_state=123).fit(vectors)
print(kmeans.labels_)

[ 8  5 18 ...  7  5  5]


In [129]:
d = {'user': users, 'label': kmeans.labels_, 'image': images}
df2 = pd.DataFrame(d, columns=['user', 'label', 'image'])
df2.head(20)

user  label                                              image
0   10892      8  ../early_predictions/images/10892/open-uri2019...
1   10892      5  ../early_predictions/images/10892/open-uri2019...
2   10892     18  ../early_predictions/images/10892/open-uri2019...
3   10892     15  ../early_predictions/images/10892/open-uri2019...
4   10892     15  ../early_predictions/images/10892/open-uri2019...
5   10892     17  ../early_predictions/images/10892/open-uri2019...
6   10892      5  ../early_predictions/images/10892/open-uri2019...
7   10892     11  ../early_predictions/images/10892/open-uri2019...
8   10892      8  ../early_predictions/images/10892/open-uri2019...
9   10892      5  ../early_predictions/images/10892/open-uri2019...
10  10892      8  ../early_predictions/images/10892/open-uri2019...
11  10892      8  ../early_predictions/images/10892/open-uri2019...
12  10892      7  ../early_predictions/images/10892/open-uri2019...
13  10892     15  ../early_predictions/images/10892/open-uri2019...
14  10892     18  ../early_predictions/images/10892/open-uri2019...
15  10892     15  ../early_predictions/images/10892/open-uri2019...
16  10892      8  ../early_predictions/images/10892/open-uri2019...
17  10892      8  ../early_predictions/images/10892/open-uri2019...
18  10892      5  ../early_predictions/images/10892/open-uri2019...
19  10892      8  ../early_predictions/images/10892/open-uri2019...

In [130]:
df2.shape

(3559, 3)

In [132]:
df2.to_csv('resnet_kmeans_20.csv', index_label=None )